version: '3'

services:
  web:
    image: nginx:stable-alpine
    volumes:
      - ./:/app
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - app

  lb:
    image: dockercloud/haproxy
    depends_on:
      - web
      - app
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:80
    environment:
      VIRTUAL_HOST: laravel.app

  app:
    image: imanilchaudhari/php-alpine
    volumes:
      - ./:/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - db
      - redis
  db:
    image: mysql:5.7.17
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel

  redis:
    image: redis:3.2-alpine

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 9001:80

  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025